MvcCoreSession/Models/ErrorViewModel.cs
namespace MvcCoreSession.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreSession/Models/Persona.cs
namespace MvcCoreSession.Models
{
    [Serializable]
    public class Persona
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }
    }
}

MvcCoreSession/Controllers/EjemploSessionController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSession.Helpers;
using MvcCoreSession.Models;

namespace MvcCoreSession.Controllers
{
    public class EjemploSessionController : Controller
    {
        int numero = 1;

        public IActionResult Index()
        {
            ViewData["NUMERO"] = "Valor del número: " + this.numero;
            return View();
        }

        public IActionResult SessionSimple(string accion)
        {
            if (accion != null)
            {
                if (accion.ToLower() == "almacenar")
                {
                    HttpContext.Session.SetString("nombre", "Programeitor");
                    HttpContext.Session.SetString("hora",
                        DateTime.Now.ToLongTimeString());
                    ViewData["MENSAJE"] = "Datos almacenados en Session";
                }
                else if (accion.ToLower() == "mostrar")
                {
                    ViewData["USUARIO"] =
                        HttpContext.Session.GetString("nombre");
                    ViewData["HORA"] =
                        HttpContext.Session.GetString("hora");
                }
            }
            return View();
        }

        public IActionResult SessionPersona(string accion)
        {
            if (accion != null)
            {
                if (accion.ToLower() == "almacenar")
                {
                    Persona persona = new Persona();
                    persona.Nombre = "Alumno";
                    persona.Email = "alumno@gmail.com";
                    persona.Edad = 25;
                    //DEBEMOS CONVERTIR EL OBJETO PERSONA
                    //A BYTE[] PARA ALMACENARLO EN SESSION
                    byte[] data = 
                        HelperBinarySession.ObjectToByte(persona);
                    //ALMACENAMOS EL OBJETO BINARIO EN SESSION
                    HttpContext.Session.Set("PERSONA", data);
                    ViewData["MENSAJE"] = "Datos almacenados";
                }
                else if (accion.ToLower() == "mostrar")
                {
                    //EXTRAEMOS EL OBJETO PERSONA DESDE LOS BYTES[]
                    //DE SESSION
                    byte[] data = HttpContext.Session.Get("PERSONA");
                    //CONVERTIMOS EL BINARIO A OBJETO
                    Persona persona = (Persona)
                        HelperBinarySession.ByteToObject(data);
                    ViewData["PERSONA"] = persona;
                }
            }
            return View();
        }

        public IActionResult ColeccionSessionPersonas(string accion)
        {
            if (accion != null)
            {
                if (accion.ToLower() == "almacenar")
                {
                    List<Persona> personas = new List<Persona>
             {
                 new Persona{ Nombre = "Lucia"
                 , Email="lucia@gmail.com", Edad = 20},
                 new Persona{ Nombre = "Andres"
                 , Email="andres@gmail.com", Edad = 40},
                 new Persona{ Nombre = "Adrian"
                 , Email="adrian@gmail.com", Edad = 23}
             };
                    byte[] data = HelperBinarySession.ObjectToByte(personas);
                    HttpContext.Session.Set("LISTAPERSONAS", data);
                    ViewData["MENSAJE"] = "Colección almacenada";
                }
                else if (accion.ToLower() == "mostrar")
                {
                    byte[] data = HttpContext.Session.Get("LISTAPERSONAS");
                    List<Persona> personas = (List<Persona>)
                        HelperBinarySession.ByteToObject(data);
                    return View(personas);
                }
            }
            return View();
        }

        public IActionResult SessionPersonaJson(string accion)
        {
            if (accion != null)
            {
                if (accion.ToLower() == "almacenar")
                {
                    Persona persona = new Persona();
                    persona.Nombre = "Alumno";
                    persona.Email = "alumno@gmail.com";
                    persona.Edad = 25;
                    string jsonPersona =
                        HelperJsonSession.SerializeObject<Persona>
                        (persona);
                    HttpContext.Session.SetString("PERSONA", jsonPersona);
                    ViewData["MENSAJE"] = "Datos almacenados";
                }
                else if (accion.ToLower() == "mostrar")
                {
                    //EXTRAEMOS EL OBJETO PERSONA DESDE EL STRING
                    string jsonPersona =
                        HttpContext.Session.GetString("PERSONA");
                    Persona persona =
                        HelperJsonSession.DeserializeObject<Persona>
                        (jsonPersona);
                    ViewData["PERSONA"] = persona;
                }
            }
            return View();
        }


    }
}

MvcCoreSession/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSession.Models;
using System.Diagnostics;

namespace MvcCoreSession.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreSession/Views/EjemploSession/ColeccionSessionPersonas.cshtml
@model IEnumerable<MvcCoreSession.Models.Persona>

@{
    ViewData["Title"] = "ColeccionSessionPersonas";
}

<h1>Coleccion Session Personas</h1>

<p>
    <a asp-controller="EjemploSession"
       asp-action="ColeccionSessionPersonas"
       asp-route-accion="almacenar">
        Almacenar colección
    </a>
</p>
<p>
    <a asp-controller="EjemploSession"
       asp-action="ColeccionSessionPersonas"
       asp-route-accion="mostrar">
        Mostrar colección
    </a>
</p>

<p>
    <a asp-action="Create">Create New</a>
</p>


@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Edad)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Edad)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreSession/Views/EjemploSession/Index.cshtml
<h1>Menú Session</h1>

<h1 style="color:blue">
    @ViewData["NUMERO"]
</h1>

<a asp-controller="EjemploSession"
 asp-action="SessionSimple">
    Session simple
</a> | 
<a asp-controller="EjemploSession"
    asp-action="SessionPersona">
    Session Persona
</a>
|
<a asp-controller="EjemploSession"
   asp-action="ColeccionSessionPersonas">
    Coleccion Personas
</a>
|
<a asp-controller="EjemploSession"
   asp-action="SessionPersonaJson">
    Session Persona Json
</a>

MvcCoreSession/Views/EjemploSession/SessionPersona.cshtml
@{
    Persona persona = ViewData["PERSONA"] as Persona;
}

<h1>Session Persona</h1>

<a asp-controller="EjemploSession"
    asp-action="SessionPersona"
    asp-route-accion="almacenar">
    Almacenar persona
</a> | 
<a asp-controller="EjemploSession"
    asp-action="SessionPersona"
    asp-route-accion="mostrar">
    Mostrar persona
</a>

|
<a asp-controller="EjemploSession"
   asp-action="ColeccionSessionPersonas"
   >
    Coleccion Personas
</a>
@if (persona != null)
{
    <h1 style="color:blue">
        Datos personales: @persona.Nombre, @persona.Email
    </h1>
    <h2 style="color:red">
        Edad: @persona.Edad
    </h2>
}

MvcCoreSession/Views/EjemploSession/SessionPersonaJson.cshtml
@{
    Persona persona = ViewData["PERSONA"] as Persona;
}

<h1 style="color:blue">Session Persona JSON</h1>

<a asp-controller="EjemploSession"
   asp-action="SessionPersonaJson"
   asp-route-accion="almacenar">
    Almacenar persona JSON
</a> |
<a asp-controller="EjemploSession"
   asp-action="SessionPersonaJson"
   asp-route-accion="mostrar">
    Mostrar persona JSON
</a>
@if (persona != null)
{
    <h1 style="color:blue">
        Datos personales: @persona.Nombre, @persona.Email
    </h1>
    <h2 style="color:red">
        Edad: @persona.Edad
    </h2>
}

MvcCoreSession/Views/EjemploSession/SessionSimple.cshtml
<h1>Session Simple</h1>

<h1 style="color:red">
    @ViewData["NUMERO"]
</h1>

<a asp-controller="EjemploSession"
 asp-action="SessionSimple"
    asp-route-accion="almacenar">
    Almacenar
</a>

<a asp-controller="EjemploSession"
    asp-action="SessionSimple" asp-route-accion="mostrar">
    Mostrar
</a>
<h3>@ViewData["MENSAJE"]</h3>

<h2 style="color:blue">
    Usuario: @ViewData["USUARIO"]
</h2>

<h2 style="color:fuchsia">
    Hora: @ViewData["HORA"]
</h2>

MvcCoreSession/Views/Home/Index.cshtml
@using MvcCoreSession.Helpers


@{
    ViewData["Title"] = "Home Page";
}
@{
    Persona persona = null;
    if(Context.Session.GetString("PERSONA") != null)
    {
        string jsonPersona = Context.Session.GetString("PERSONA");
            persona =
            HelperJsonSession.DeserializeObject<Persona>(jsonPersona);
    }
   
}
<div class="text-center">
    <h1 class="display-4">Proyecto Session</h1>
    <p>Hora: @Context.Session.GetString("hora")</p>
    <p>Nombre: @Context.Session.GetString("nombre")</p>

    @if(persona != null)
    {
        <h1 style="color:blue">
            Persona: @persona.Nombre, @persona.Email
        </h1>
        <h1 style="color:red">
            Edad Persona: @persona.Edad
        </h1>
    }
    

</div>

MvcCoreSession/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreSession</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreSession.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreSession</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="EjemploSession" 
                            asp-action="Index">
                                Ejemplos Session
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreSession - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>